### ISSUE TITLE
Cannot import name 'Tenor' from 'tenorpy.tenorpy'

### ISSUE THREAD

**Issue by mr0x13f** [miditkl/TenGiphPy#1]
Importing the library throws ImportError "cannot import name 'Tenor' from 'tenorpy.tenorpy'"
This can be solved by removing
`if __name__ == "__main__":`
on line 29 from tenorpy.py.

**Comment by miditkl** [comment]
i fixed it. let me know if it works so i can close this issue.

**Comment by mr0x13f** [comment]
It works, thank you!
