### ISSUE TITLE
import geht net pls help

### ISSUE THREAD

**Issue by phillipyosief** [miditkl/TenGiphPy#3]

**Comment by miditkl** [comment]
Beschreibe dein Fehler. Code, Error. Diese Infos fehlen mir. Öffne dein Issue erneut, solltest du es doch beschreiben können.


Grüße Snosh ^^

**Comment by phillipyosief** [comment]
oha sry bei mein pi geht des net ka why


Am Fr., 22. Mai 2020 um 01:08 Uhr schrieb Midian T. <
notifications@github.com>:
