### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ghost** [miditkl/TenGiphPy#4]
`from tenorpy.tenorpy import Tenor
ImportError: cannot import name 'Tenor' from 'tenorpy.tenorpy' (/home/pi/.local/                                          lib/python3.7/site-packages/tenorpy/tenorpy.py)
`

**Comment by miditkl** [comment]
```py
import tenorpy
t = tenorpy.Tenor()
```
or
```py
from tenorpy import Tenor
t = Tenor()
```

Let me know if it worked so i can close the issue.

**Comment by ghost** [comment]
> 
> 
> ```python
> import tenorpy
> t = tenorpy.Tenor()
> ```
> 
> or
> 
> ```python
> from tenorpy import Tenor
> t = Tenor()
> ```
> 
> Let me know if it worked so i can close the issue.

I use that, it works on windows but dont works on raspbian

**Comment by miditkl** [comment]
Update tenorpy. ``pip install -U tenorpy`` or ``python3 -m pip install -U tenorpy``

**Comment by ghost** [comment]
> 
> 
> Update tenorpy. `pip install -U tenorpy` or `python3 -m pip install -U tenorpy`

i allready use it

**Comment by LouissXI** [comment]
I have the same issue on raspbian, Nobody can help ?
`Traceback (most recent call last):
  File "main.py", line 8, in <module>
    import tenorpy
  File "/usr/local/lib/python3.7/dist-packages/tenorpy/__init__.py", line 1, in <module>
    from tenorpy.tenorpy import Tenor
ImportError: cannot import name 'Tenor' from 'tenorpy.tenorpy' (/usr/local/lib/python3.7/dist-packages/tenorpy/tenorpy.py)`

**Comment by miditkl** [comment]
Use TenGiphPy instead:

Uninstall Tenorpy `pip uninstall tenorpy`
Install TenGiphPy `pip install TenGiphPy`

You need a API Token fpr tenor and giphy. More infos: [Readme](https://github.com/realSnosh/TenGiphPy/blob/version-2.0.0/README.md)

Hope it will solve your problem.
