### ISSUE TITLE
repetitive gifs

### ISSUE THREAD

**Issue by nonetrix** [miditkl/TenGiphPy#5]
I've been using this for a bot on mastodon(twitter clone) but the gifs are repetitive most likely due to it not loading many gifs it would be nice if you could set a max if you can't already

**Comment by miditkl** [comment]
Use TenGiphPy instead:

Uninstall Tenorpy `pip uninstall tenorpy`
Install TenGiphPy `pip install TenGiphPy`

You need a API Token fpr tenor and giphy. More infos: [Readme](https://github.com/realSnosh/TenGiphPy/blob/version-2.0.0/README.md)
