### ISSUE TITLE
add support for python3.9

### ISSUE THREAD

**Issue by owocado** [miditkl/TenGiphPy#6]
Hi, this is a nice API wrapper for Tenor. Please add support for python 3.9. Thanks.

**Comment by miditkl** [comment]
I'll rewrite it and add Giphy support for Py3.9

**Comment by miditkl** [comment]
New Update: use TenGiphPy

Uninstall Tenorpy `pip uninstall tenorpy`
Install TenGiphPy `pip install TenGiphPy`

You need a API Token fpr tenor and giphy. More infos: [Readme](https://github.com/realSnosh/TenGiphPy/blob/version-2.0.0/README.md)

**Comment by owocado** [comment]
wonderful. thank you very much. ❤️ 😘
